# set-option -g default-shell /usr/bin/zsh
set -g mouse on
set -g set-clipboard on
set -ga terminal-overrides ",*:RGB"
bind -n M-Enter new-window
bind -n M-r source-file ~/.config/tmux/tmux.conf \; display "config reloaded"

unbind %
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

unbind C-b
set -g prefix C-s

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

bind -n S-Left previous-window
bind -n S-Right next-window
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# thm_bg="#000000"
# thm_fg="#e8e8e8"
# thm_cyan="#8ec07c"
# thm_black="#0f0f0f"
# thm_gray="#666666"
# thm_magenta="#d3869b"
# thm_pink="#c9b89a"
# thm_red="#fb4934"
# thm_green="#b8bb26"
# thm_yellow="#d79921"
# thm_blue="#458588"
# thm_orange="#d65d0e"
# thm_black4="#2a2a2a"


# thm_bg="#1e1e2e"
# thm_fg="#cdd6f4"
# thm_cyan="#94e2d5"
# thm_black="#181825"
# thm_gray="#6c7086"
# thm_magenta="#cba6f7"
# thm_pink="#f5e0dc"
# thm_red="#f38ba8"
# thm_green="#a6e3a1"
# thm_yellow="#f9e2af"
# thm_blue="#89b4fa"
# thm_orange="#fab387"
# thm_black4="#313244"

thm_bg="#101010"
thm_fg="#d6d6d6"
thm_cyan="#d0d0d0"
thm_black="#0a0a0a"
thm_gray="#717171"
thm_magenta="#b4b4b4"
thm_pink="#e4e4e4"
thm_red="#a3a3a3"
thm_green="#d1d1d1"
thm_yellow="#e3e3e3"
thm_blue="#b0b0b0"
thm_orange="#bfbfbf"
thm_black4="#262626"


set -g status "on"
set -g status-bg "${thm_bg}"
set -g status-fg "${thm_fg}"

set -g status-justify "centre"

set -g status-left ""
set -g status-right ""

set -g window-status-format "#[fg=${thm_gray},bg=${thm_bg}] #I:#W "

# set -g window-status-current-format "#[fg=${thm_blue},bg=${thm_bg}] #I: #[fg=${thm_cyan},bg=${thm_bg}]#(echo '#{pane_current_path}' | rev | cut -d'/' -f-2 | rev) "
# set -g window-status-current-format "#[fg=${thm_blue},bg=${thm_bg}]#I:#[fg=${thm_cyan},bg=${thm_bg}]#{pane_current_command}"
set -g window-status-current-format "#[fg=${thm_cyan},bg=${thm_bg}] #I:#W "

set -g window-status-separator ""

set -g message-style "fg=${thm_cyan},bg=${thm_gray},align=centre"
set -g message-command-style "fg=${thm_cyan},bg=${thm_gray},align=centre"
set -g pane-border-style "fg=${thm_gray}"
set -g pane-active-border-style "fg=${thm_blue}"
set -g window-status-activity-style "fg=${thm_fg},bg=${thm_bg},none"
set -g window-status-style "fg=${thm_fg},bg=${thm_bg},none"
set -g clock-mode-colour "${thm_blue}"
set -g mode-style "fg=${thm_blue} bg=${thm_black4} bold"
